# the name of the workflow in the UI, otherwise it will be the path to the file
name: CI for dagger

on:
  push:
    branches:
      - main

  # allow manual dispatch of the workflow
  workflow_dispatch:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:

      # Checkout the project code
      - name: Checkout
        uses: actions/checkout@v4
      

      - name: Call Dagger Function - test
        uses: dagger/dagger-for-github@v5
        with:
          version: "latest"
          verb: call
          module: ./dagger
          args: test --source=.

      - name: Call Dagger Function - build
        uses: dagger/dagger-for-github@v5
        with:
          version: "latest"
          verb: call
          module: ./dagger
          args: build --source=.
  
