# the name of the workflow in the UI, otherwise it will be the path to the file
name: CI for dagger

on:
  push:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:

      # Checkout the project code
      - name: Checkout
        uses: actions/checkout@v4
      
      # - name: setup go
      #   uses: actions/setup-go@v3
      #   with:
      #     go-version: 1.23
      #     cache: false
      #     check-latest: false

      - name: Call Dagger Function
        uses: dagger/dagger-for-github@v5
        with:
          version: "latest"
          verb: call
          # assumes a Go project
          # modify to use different function(s) as needed
          module: ./dagger
          args: test --source=.
          # assumes the Dagger Cloud token is in
          # a repository secret named DAGGER_CLOUD_TOKEN
          # set via the GitHub UI/CLI
          # cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        # env:
        #   GO111MODULE: off
